server {
  listen ${PORT};
  listen [::]:${PORT};
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  types {
    text/html                             html;
    text/css                              css;
    application/javascript                js mjs;
    application/json                      json;
    image/webp                            webp;
    image/png                             png;
    image/jpeg                            jpg jpeg;
    image/svg+xml                         svg;
    model/gltf-binary                     glb;
    font/woff2                            woff2;
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
  add_header Pragma "no-cache" always;
  expires -1;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
