server {
  listen ${PORT};
  listen [::]:${PORT};
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  types {
    text/html                             html;
    text/css                              css;
    application/javascript                js mjs;
    application/json                      json;
    image/webp                            webp;
    image/png                             png;
    image/jpeg                            jpg jpeg;
    image/svg+xml                         svg;
    model/gltf-binary                     glb;
    font/woff2                            woff2;
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  location /assets/ {
    add_header Cache-Control "public, max-age=604800";
  }

  location ~* \.(css|js)$ {
    add_header Cache-Control "no-cache";
  }

  location ~* \.html$ {
    add_header Cache-Control "no-cache";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
